boilerplate/apps/subscriptions/urls.py
from django.urls import path

from . import views


app_name = 'subscriptions'
urlpatterns = [

    # user-specific URLs
    path('', views.subscription, name='subscription_details'),
    path('subscription_success/', views.subscription_success, name='subscription_success'),
    path('demo/', views.subscription_demo, name='subscription_demo'),
    path('subscription-gated-page/', views.subscription_gated_page, name='subscription_gated_page'),
    path('stripe-portal/', views.create_stripe_portal_session, name='create_stripe_portal_session'),
    path('api/create_customer/', views.create_customer, name='create_customer'),

]

boilerplate/apps/web/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from . import views

app_name = 'web'
urlpatterns = [
    path(r'', views.home, name='home'),
    path(r'analyze', views.analyze, name='analyze'),
    path(r'options', views.options, name='options'),
    path(r'resources', views.resources, name='resources'),
    path(r'scraper', views.scraper, name='scraper'),

    path(r'terms', TemplateView.as_view(
        template_name="web/terms.html"), name='terms'),
]

boilerplate/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework.documentation import include_docs_urls, get_schemajs_view
from django.views.static import serve 

schemajs_view = get_schemajs_view(title="API")


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.users.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),
   re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 

    path('', include('apps.web.urls')),
    path('pegasus/', include('pegasus.apps.examples.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    # these are needed for schema.js
    path('docs/', include_docs_urls(title='API Docs')),
    path('schemajs/', schemajs_view, name='api_schemajs'),

    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boilerplate/templates/web/components/favicon.html
{# see https://realfavicongenerator.net #}
<link rel="apple-touch-icon" sizes="180x180" href="/static/images/favicons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/static/images/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/static/images/favicons/favicon-16x16.png">
<link rel="manifest" href="/static/images/favicons/site.webmanifest">
<link rel="mask-icon" href="/static/images/favicons/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/static/images/favicons/favicon.ico">
<meta name="msapplication-TileColor" content="#603cba">
<meta name="msapplication-config" content="/static/images/favicons/browserconfig.xml">
<meta name="theme-color" content="#ffffff">

boilerplate/templates/web/components/footer.html
<div class="f09_container">
      <div class="f09_line"></div>
      <div class="f09_columns w-row">
        <div class="f09_column w-col w-col-4 w-col-stack"><img src="/static/images/stockk.png" width="130" alt="logo" class="f09_logo">
          <p class="f09_paragraph">Have questions about Stockk? We've got all the answers you need. Shoot us an email and we'll get back to you shortly.</p><a href="#" class="f09_link_wrap w-inline-block"><img src="https://uploads-ssl.webflow.com/5d01778cda7c6cc8a63e0b64/5d1324fd4b05c818c6fbecc1_mail.svg" width="19" alt="" class="f09_icon"><p class="f09_text">contact@stockk.io</p></a>
</div>


        <div class="f09_column w-col w-col-2 w-col-stack">
          <div class="f09_title"></div><a href="#" class="f09_link"></a><a href="#" class="f09_link"></a><a href="#" class="f09_link"></a></div>
        <div class="f09_column w-col w-col-3 w-col-stack">

          
          <div class="f09_title"></div><a href="#" class="f09_link"></a><a href="#" class="f09_link"></a><a href="#" class="f09_link"></a></div>
        <div class="f09_column w-col w-col-3 w-col-stack">
          <div class="f09_title"></div>
          <div class="f09_social_wrap">

            <!-- <div class="f09_social"><img src="/static/images/forest_facebook_w.svg" alt="" class="f09_social_icon"><a href="#" class="f09_social_link w-inline-block"></a></div> -->
            <!-- <div class="f09_social"><img src="/static/images/forest_linkedin_w.svg" alt="" class="f09_social_icon"><a href="#" class="/static/f09_social_link w-inline-block"></a></div> -->
            <div class="f09_social"><img src="/static/images/forest_twitter_w.svg" alt="" class="f09_social_icon"><a href="https://twitter.com/stockkio" class="f09_social_link w-inline-block"></a></div>
          </div>
        </div>
      </div>
    </div>

boilerplate/templates/web/components/google_analytics.html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ GOOGLE_ANALYTICS_ID  }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{{ GOOGLE_ANALYTICS_ID  }}');
</script>

boilerplate/templates/web/components/messages-js.html
<script type="application/javascript">
    document.addEventListener('DOMContentLoaded', () => {
      (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
        let $notification = $delete.parentNode;
        $delete.addEventListener('click', () => {
          $notification.parentNode.removeChild($notification);
        });
      });
    });
</script>

boilerplate/templates/web/components/messages.html
{% if messages %}
    {% for message in messages %}
    {% if message.level_tag == "success" %}
    <div class="alert_6">
    	{% else %}
    	<div class="alert_{{message.level_tag}}">
    {% endif %}



  <div class="alert_content_wrap">
    <div class="alert_line_2"></div>
    <div class="paragraph-2-a">{{ message }}</div>
</div>
</div>
    {% endfor %}
{% endif %}

boilerplate/templates/web/components/meta.html
{% load meta_tags %}
{% load static %}
{% if project_meta %}
{% with project_meta|get_title:page_title as title %}
{% with project_meta|get_description:page_description as description %}
{% with project_meta|get_image_url:page_image as image %}
    <title>{{ title }}</title>
    <meta name="description" content="{{ description }}">
    <meta name="keywords" content="{{ project_meta.KEYWORDS }}">
    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="{{ title }}">
    <meta name="twitter:description" content="{{ description }}">
    <meta name="twitter:image" content="{{ image }}">
    <!-- Open Graph data -->
    <meta property="og:title" content="{{ title }}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="{{ page_url }}" />
    <meta property="og:image" content="{{ image }}" />
    <meta property="og:description" content="{{ description }}" />
    <meta property="og:site_name" content="{{ project_meta.NAME }}" />
    <link rel="canonical" href="{% if page_canonical_url %}{{ page_canonical_url }}{% else %}{{ page_url }}{% endif %}">
{% endwith %}
{% endwith %}
{% endwith %}
{% endif %}

boilerplate/templates/web/components/navbar-js.html
<script type="application/javascript">
    // see: https://bulma.io/documentation/components/navbar/
    document.addEventListener('DOMContentLoaded', () => {
        // Get all "navbar-burger" elements
        const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
        // Check if there are any navbar burgers
        if ($navbarBurgers.length > 0) {
            // Add a click event on each of them
            $navbarBurgers.forEach(el => {
                el.addEventListener('click', () => {
                    // Get the target from the "data-target" attribute
                    const target = el.dataset.target;
                    const $target = document.getElementById(target);

                    // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                    el.classList.toggle('is-active');
                    $target.classList.toggle('is-active');
                });
            });
        }
    });
</script>

boilerplate/templates/web/components/team_nav.html
{% load team_tags %}
{% if request.team and request.user|is_admin_of:request.team %}
  <li>
      <a href="{% url 'web:team_admin' request.team.slug %}" {% if active_tab == 'team-admin' %}class="is-active"{% endif %}>
          <span class="icon"><i class="fa fa-gear"></i></span><span class="is-hidden-tablet-only">Admin</span>
      </a>
  </li>


  <li>
      <a href="{% url 'subscriptions:team_subscription_demo' request.team.slug %}" {% if active_tab == 'subscription_demo' %}class="is-active"{% endif %}>
          <span class="icon"><i class="fa fa-desktop"></i></span><span class="is-hidden-tablet-only">Subscription Demo</span>
      </a>
  </li>
  <li>
      <a href="{% url 'subscriptions:team_subscription_details' request.team.slug %}" {% if active_tab == 'subscription' %}class="is-active"{% endif %}>
          <span class="icon"><i class="fa fa-repeat"></i></span><span class="is-hidden-tablet-only">Subscription</span>
      </a>
  </li>


{% endif %}

boilerplate/templates/web/components/top_nav.html
 

    <header class="forest_nav">
      <div data-collapse="medium" data-animation="default" data-duration="400" role="banner" class="nav03 w-nav">
        <div class="nav03_container">
          <div class="nav03_left">

            <a href="#" class="nav03_logo w-nav-brand"><img src="/static/images/stockk.png" width="120" alt="" class="nav03_logo_image"></a>
          </div>

          <nav role="navigation" class="nav03_links w-nav-menu">

            <a href="{% url 'web:home' %}" class="nav03_link w-nav-link">Home</a>

            
            <a href="{% url 'web:scraper' %}" class="nav03_link w-nav-link">Scraper</a>


            <a href="{% url 'web:analyze' %}" class="nav03_link w-nav-link">Analyzer</a>
          

            <a href="{% url 'web:options' %}" class="nav03_link w-nav-link">Options</a>


            <a href="{% url 'web:resources' %}" class="nav03_link w-nav-link">Resources</a>


          </nav>
          {% if user.is_authenticated %}


          <div data-delay="0" class="dropdown-round w-dropdown" role="menu" aria-labelledby="w-dropdown-toggle-8" style=""><div class="dropdown_round w-dropdown-toggle" tabindex="0" id="w-dropdown-toggle-8" aria-controls="w-dropdown-list-8" aria-haspopup="menu" style="outline: none;"><div class="w-icon-dropdown-toggle"></div>


          <div>Account</div></div>
          <nav class="dropdown_list w-dropdown-list" id="w-dropdown-list-8">

            <a href="{% url 'subscriptions:subscription_details' %}" class="dropdown_link w-dropdown-link" tabindex="-1" role="menuitem" style="outline: none;">Upgrade Account</a>

            <a href="{% url 'account_change_password' %}" class="dropdown_link w-dropdown-link" tabindex="-1" role="menuitem" style="outline: none;">Change Password</a>

            <a href="{% url 'account_logout' %}"  class="dropdown_link w-dropdown-link"  tabindex="-1" role="menuitem" style="outline: none;">Logout</a>
                   

        </a>
          </nav></div>

          {% else %}
          <div class="nav03_right"><a href="{% url 'account_login' %}" class="nav03_button w-button">LOGIN</a>
                      <div class="nav03_right"><a href="{% url 'account_signup' %}" class="nav03_button w-button">SIGN UP</a>


            <div class="nav03_menu_button w-nav-button">
              <div class="nav03_icon w-icon-nav-menu"></div>
            </div>
          </div>
        </div>
        {% endif %}

      </div>
    </header>
  </div>

  <!-- {% include 'web/components/messages.html' %} -->