boilerplate/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework.documentation import include_docs_urls, get_schemajs_view
from django.views.static import serve 

schemajs_view = get_schemajs_view(title="API")


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.users.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),
   re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 

    path('', include('apps.web.urls')),
    path('pegasus/', include('pegasus.apps.examples.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    # these are needed for schema.js
    path('docs/', include_docs_urls(title='API Docs')),
    path('schemajs/', schemajs_view, name='api_schemajs'),

    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boilerplate/pegasus/apps/examples/urls.py
from django.urls import path
from django.views.generic import TemplateView
from rest_framework import routers

from . import views


app_name = 'pegasus_examples'

urlpatterns = [
    path(r'', views.ExamplesHomeView.as_view(), name='examples_home'),
    path(r'payments', views.PaymentView.as_view(), name='payments'),
    path(r'payments/create/', views.accept_payment, name='accept_payment'),
    path(r'payments/confirm/<slug:payment_id>/', views.payment_confirm, name='payment_confirm'),
    path(r'landing_page/', TemplateView.as_view(template_name='pegasus/examples/example_landing_page.html'),
         name='landing_page'),
    path(r'pricing_page/', TemplateView.as_view(template_name='pegasus/examples/example_pricing_page.html'),
         name='pricing_page'),
    path(r'objects/react/', views.ReactObjectLifecycleView.as_view(), name='react_object_lifecycle'),
    path(r'objects/react/<path:path>', views.ReactObjectLifecycleView.as_view(), name='react_object_lifecycle_w_path'),
    path(r'objects/vue/', views.VueObjectLifecycleView.as_view(), name='vue_object_lifecycle'),
    path(r'charts/', views.ChartsView.as_view(), name='charts'),
    path(r'tasks/', views.TasksView.as_view(), name='tasks'),
    path(r'tasks/api/', views.tasks_api, name='tasks_api'),

    path(r'api/employee-data/', views.EmployeeDataAPIView.as_view(), name='employee_data'),
]


# drf config
router = routers.DefaultRouter()
router.register(r'api/employees', views.EmployeeViewSet)

urlpatterns += router.urls

boilerplate/pegasus/apps/examples/models/objects.py
from django.conf import settings
from django.db import models

from apps.utils.models import BaseModel


class Employee(BaseModel):
    DEPARTMENT_CHOICES = (
        ('hr', 'Human Resources'),
        ('finance', 'Finance'),
        ('engineering', 'Engineering'),
        ('marketing', 'Marketing'),
        ('sales', 'Sales'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='employees')
    name = models.CharField(max_length=100)
    department = models.CharField(max_length=20, choices=DEPARTMENT_CHOICES)
    salary = models.PositiveIntegerField()

    def __str__(self):
        return self.name

boilerplate/pegasus/apps/examples/models/payments.py
import uuid

from django.conf import settings
from django.db import models

from apps.utils.models import BaseModel


class Payment(BaseModel):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    charge_id = models.CharField(max_length=100, help_text='The stripe charge ID associated with this payment.')
    name = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='pegasus_payments')
    amount = models.PositiveIntegerField(help_text='In cents')

    @property
    def payment_id(self):
        return str(self.id)

    @property
    def amount_display(self):
        return '${:,.2f}'.format(self.amount / 100.)

boilerplate/pegasus/apps/examples/views/objects.py
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Sum, Count
from django.templatetags.static import static
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.views import APIView

from ..models import Employee
from ..serializers import EmployeeSerializer


@method_decorator(login_required, name='dispatch')
class ObjectLifecycleView(TemplateView):
    def get_context_data(self, **kwargs):
        return {
            'department_choices': [{
                'id': c[0],
                'name': c[1]
            } for c in Employee.DEPARTMENT_CHOICES],
        }


class ReactObjectLifecycleView(ObjectLifecycleView):
    template_name = 'pegasus/examples/objects/react_object_lifecycle.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'framework_url': 'https://reactjs.org/',
            'framework_name': 'React',
            'framework_icon': static('images/pegasus/react-icon.png'),
            'active_tab': 'react_object_lifecycle',
        })
        return context


class VueObjectLifecycleView(ObjectLifecycleView):
    template_name = 'pegasus/examples/objects/vue_object_lifecycle.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'framework_url': 'https://vuejs.org/',
            'framework_name': 'Vue.js',
            'framework_icon': static('images/pegasus/vue-icon.png'),
            'active_tab': 'vue_object_lifecycle',
        })
        return context


@method_decorator(login_required, name='dispatch')
class ChartsView(TemplateView):
    template_name = 'pegasus/examples/objects/charts.html'

    def get_context_data(self, **kwargs):
        return {
            'active_tab': 'charts',
        }


class EmployeeDataAPIView(APIView):

    def get(self, request):
        data = request.user.employees.values('department').annotate(
            average_salary=Avg('salary'),
            total_cost=Sum('salary'),
            number_employees=Count('pk'),
        )
        # data will look something like this:
        # [
        #     {'total_cost': 132000, 'number_employees': 2, 'average_salary': 66000.0, 'department': 'hr'},
        #     {'total_cost': 60000, 'number_employees': 1, 'average_salary': 60000.0, 'department': 'marketing'}
        # ]
        total_costs = [
            [row['department'], row['total_cost']] for row in data
        ]
        average_salaries = [
            [row['department'], row['average_salary']] for row in data
        ]
        headcounts = [
            [row['department'], row['number_employees']] for row in data
        ]
        return Response({
            'total_costs': total_costs,
            'average_salaries': average_salaries,
            'headcounts': headcounts,
        })


class EmployeeViewSet(viewsets.ModelViewSet):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer

    def get_queryset(self):
        # filter queryset based on logged in user
        return self.request.user.employees.all()

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

boilerplate/pegasus/apps/examples/views/payments.py
import stripe
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from apps.utils.decorators import catch_stripe_errors
from ..models import Payment

EXPECTED_PAYMENT_AMOUNT = 2500  # in cents

@method_decorator(login_required, name='dispatch')
class PaymentView(TemplateView):
    template_name = 'pegasus/examples/payments/payments.html'

    def get_context_data(self, **kwargs):
        return {
            'stripe_key': settings.STRIPE_TEST_PUBLIC_KEY,
            'payments': self.request.user.pegasus_payments.all(),
            'amount': EXPECTED_PAYMENT_AMOUNT,
            'active_tab': 'payments',
        }


@login_required
def payment_confirm(request, payment_id):
    """
    Confirmation page after making a payment.
    """
    payment = get_object_or_404(Payment, user=request.user, id=payment_id)
    return render(request, 'pegasus/examples/payments/payment_confirm.html', {
        'payment': payment,
        'active_tab': 'payments',
    })


@login_required
@require_POST
@catch_stripe_errors
def accept_payment(request):
    """
    Accept a payment with a token from Stripe
    """
    amount = int(request.POST['amount'])

    # since this value is coming from the front-end, we need to double-check it is correct
    if amount != EXPECTED_PAYMENT_AMOUNT:
        raise ValueError('Received unexpected payment amount {}'.format(amount))

    name = request.POST['name']
    token = request.POST['stripeToken']
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    user = request.user
    email = request.user.email
    charge = stripe.Charge.create(
        amount=amount,
        currency="usd",
        description=name,
        source=token,
        receipt_email=email,
    )
    payment = Payment.objects.create(
        charge_id=charge.id,
        amount=charge.amount,
        name=name,
        user=user,
    )
    return HttpResponseRedirect(reverse('pegasus_examples:payment_confirm', args=[payment.payment_id]))

boilerplate/pegasus/apps/examples/views/tasks.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from ..tasks import progress_bar_task


@method_decorator(login_required, name='dispatch')
class TasksView(TemplateView):
    template_name = 'pegasus/examples/tasks.html'

    def get_context_data(self, **kwargs):
        return {
            'active_tab': 'tasks',
        }


@require_POST
def tasks_api(request):
    result = progress_bar_task.delay(5)
    return HttpResponse(result.task_id)

boilerplate/templates/pegasus/examples/example_landing_page.html
{% extends "web/base.html" %}
{% load static %}
{% block body %}
<section class="notification is-warning has-text-centered app-notice">
    <p>
        This is the example landing page that ships with Pegasus, which is heavily-based on Pegasus's own landing page.
    </p>
    <p>
        <a href="{% url 'pegasus_examples:examples_home' %}">Back to examples</a>.
    </p>
</section>
<div id="example-page-content">
<section class="section container">
    <div class="columns columns-reversed">
        <div class="column">
            <img src="{% static 'images/undraw/undraw_outer_space.svg' %}" alt="Fly Away!">
        </div>
        <div id="tagline" class="column">
            <h1 class="title is-size-2">My Amazing SaaS Application</h1>
            <h2 class="subtitle is-size-4">
                This app will be the greatest thing the world has ever seen.
            </h2>
            <p class="buttons">
                <a class="button is-primary is-large" href="#get-started">
                    Get Started
                </a>
                <a class="button is-primary is-large is-outlined" href="#pricing">
                    Pricing
                </a>
            </p>
        </div>
    </div>
</section>
<section class="section container is-size-5">
    <div class="columns">
        <div class="column is-one-quarter">
            <img src="{% static 'images/undraw/undraw_features_overview.svg' %}" alt="Powerful Built-In Features">
        </div>
        <div class="is-three-quarters">
            <div class="title">Powerful Built-In Features</div>
            <div class="subtitle">This is where you talk about the great features that your app has.</div>
            <div class="columns">
                <div class="column">
                    <span class="subfeature-title">Feature Number 1</span>
                    &mdash; A really great feature that everyone will love!
                </div>
                <div class="column">
                    <span class="subfeature-title">Feature Number 2</span>
                    &mdash; This feature is even better than Feature #1! A real crowd pleaser!
                </div>
                <div class="column">
                    <span class="subfeature-title">Feature 3</span>
                    &mdash; Possibly the best feature of all. This is some groundbreaking stuff that this app can do.
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section container is-size-5">
    <div class="columns columns-reversed">
        <div class="column is-one-quarter">
            <img src="{% static 'images/undraw/undraw_portfolio_update.svg' %}" alt="Examples">
        </div>
        <div class="is-three-quarters">
            <div class="title">Another Section of Functionality</div>
            <div class="subtitle">Here you can add more things that you want to talk about.</div>
            <div class="columns">
                <div class="column">
                    <span class="subfeature-title">Extra Thing 1</span>
                    &mdash;This thing is important so it will be listed first.
                </div>
                <div class="column">
                    <span class="subfeature-title">Extra Thing 2</span>
                    &mdash;This thing is not as important as the first thing, so we've listed it second.
                </div>
                <div class="column">
                    <span class="subfeature-title">Extra Thing 2</span>
                    &mdash;This is the least important thing in this section.
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section container is-size-5">
    <div class="columns">
        <div class="column is-one-quarter">
            <img src="{% static 'images/undraw/undraw_coding.svg' %}" alt="Build With Django">
        </div>
        <div class="is-three-quarters">
            <div class="title">A Third Section</div>
            <div class="subtitle">You are probably getting the picture now, but you can put as many of these sections as you want.</div>
            <div class="columns">
                <div class="column">
                    <span class="subfeature-title">Third Section Item 1</span>
                    &mdash;You don't have to have three items in each section. This one only has two.
                    The text here is a bit longer because we want to fill the space.
                </div>
                <div class="column">
                    <span class="subfeature-title">Third Section Item 2</span>
                    &mdash;This is the last one in this section. Phew, that was repetetive!
                    Now we can move onto a different layout / section of the page.
                </div>
            </div>
        </div>
    </div>
</section>
<section class="hero is-primary" >
    <div class="hero-body">
        <div class="container has-text-centered ">
            <h2 class="subtitle is-size-4 has-text-white">
                Just <del>$200</del> <strong>$99</strong> per month for new users! What a deal!
            </h2>
            <a class="button is-primary is-inverted is-medium" href="#get-started">
                Get Started
            </a>
        </div>
    </div>
</section>
<section class="section container is-size-5" id="faq">
    <div class="title">Frequently Asked Questions</div>
    <div class="columns question">
        <div class="column is-one-third has-text-weight-bold">
            What's this section all about?
        </div>
        <div class="column is-two-thirds">
            It's a simple two-column format that works great for a back and forth dialog
            like an FAQ.
        </div>
    </div>
    <div class="columns question">
        <div class="column is-one-third has-text-weight-bold">
            What does your app do?
        </div>
        <div class="column is-two-thirds content">
            <p>What <em>doesn't</em> the app do?</p>
            <p>It will solve all of your problems and a few problems you didn't even know you had!</p>
        </div>
    </div>
    <div class="columns question">
        <div class="column is-one-third has-text-weight-bold">
            What else can you tell me?
        </div>
        <div class="column is-two-thirds content">
            <p>
                Not too much. Each application is a unique snowflake and you'll have to come up with
                the right message for your application.
                This is just a layout to get you started!
            </p>
        </div>
    </div>
</section>
</div>
{% endblock %}
{% block page_js %}
{% include 'pegasus/examples/components/sticky-header-js.html' %}
{% endblock %}

boilerplate/templates/pegasus/examples/example_pricing_page.html
{% extends "web/base.html" %}
{% load static %}
{% block body %}
<section class="notification is-warning has-text-centered app-notice">
    <p>
        This is the example pricing page that ships with Pegasus, which is heavily-based on Pegasus's own pricing page.
    </p>
    <p>
        <a href="{% url 'pegasus_examples:examples_home' %}">Back to examples</a>.
    </p>
</section>
<div id="example-page-content">
<div class="hero" id="pricing-page-head">
    <div class="hero-body has-text-centered">
        <div class="container">
            <div class="title">
                Choose the plan that's right for you
            </div>
            <div class="subtitle">
                Jump start your side project, or settle in for the long haul.
            </div>
        </div>
    </div>
</div>
<section id="plans">
    <div id="plan-wrapper" class="container">
        <div class="plan">
            <div class="plan-summary">
                <div class="plan-info">
                    <h2 class="title">Trial</h2>
                    <h3 class="subtitle">Trial all functionality for 30 days.</h3>
                </div>
                <div class="plan-price">
                    <p class="price">Free</p>
                    <p class="price-detail">forever</p>
                    <a class="button is-primary is-outlined is-medium" href="#sign-up">Try Now</a>
                </div>
            </div>
            <div class="plan-details">
                <ul>
                    <li>Free sign up</li>
                    <li>Demo all features</li>
                </ul>
            </div>
        </div>
        <div class="plan is-active">
            <div class="plan-highlight">
                <p>Most Popular</p>
            </div>
            <div class="plan-summary">
                <div class="plan-info">
                    <h2 class="title">Professional</h2>
                    <h3 class="subtitle">The choice for professional organizations.</h3>
                </div>
                <div class="plan-price">
                    <p style="margin-top: .5em; margin-bottom: .5em"><span class="tag is-warning is-rounded">early bird price!</span></p>
                    <p class="price"><del class="has-text-grey-light">$200</del> $99</p>
                    <p class="price-detail">per month</p>
                    <a class="button is-primary is-medium" href="#sign-up">Purchase</a>
                </div>
            </div>
            <div class="plan-details">
                <ul>
                    <li>A great thing you get on this plan</li>
                    <li>Another benefit of this plan</li>
                    <li>And a third thing that makes this a great choice</li>
                </ul>
            </div>
        </div>
        <div class="plan">
            <div class="plan-summary">
                <div class="plan-info">
                    <h2 class="title">Enterprise</h2>
                    <h3 class="subtitle">For the enterprise that needs the most.</h3>
                </div>
                <div class="plan-price">
                    <p class="price">$1000</p>
                    <p class="price-detail">per month</p>
                    <a class="button is-primary is-outlined is-medium" href="#contact">Contact Us</a>
                </div>
            </div>
            <div class="plan-details">
                <ul>
                    <li>Advanced security and compliance</li>
                    <li>24/7 support</li>
                    <li>Another benefit only available to enterprise customers</li>
                </ul>
            </div>
        </div>
    </div>
</section>
</div>
{% endblock %}
{% block page_js %}
{% include 'pegasus/examples/components/sticky-header-js.html' %}
{% endblock %}

boilerplate/templates/pegasus/examples/examples_base.html
{% extends "web/app/app_base.html" %}
{% block sidebar-nav %}
    {% include "pegasus/examples/components/examples_nav.html" %}
{% endblock %}

boilerplate/templates/pegasus/examples/examples_home.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% block app %}
<section class="app-card">
  <h1 class="title">Examples Gallery</h1>
  <h2 class="subtitle">
    End-to-end, fully functional examples for your project's needs.
  </h2>
  <div class="columns">
    <div class="column">
      <div class="card h-100">
        <div class="card-image">
          <figure class="image is-3by2">
            <img src="{% static 'images/undraw/undraw_credit_card.svg' %}" alt="Payments">
          </figure>
        </div>
        <div class="card-content dashboard-card-content">
          <div class="content">
            <h3>Payments</h3>
            <p>
              Easily collect once-off credit card payments using Stripe
              with this complete example.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_examples:payments' %}" class="button is-primary is-outlined">
              <span>View Payments</span>
              <span class="icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="column">
      <div class="card h-100">
        <div class="card-image">
          <figure class="image is-3by2">
            <img src="{% static 'images/pegasus/react-vue-icons.png' %}" alt="Object Demo">
          </figure>
        </div>
        <div class="card-content dashboard-card-content">
          <div class="content">
            <h3>Object Lifecycle</h3>
            <p>
              A single-page front-end for manipulating objects implemented in both React and Vue.js.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_examples:react_object_lifecycle' %}" class="button is-primary is-outlined">
              <span>React Demo</span>
              <span class="icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
            <a href="{% url 'pegasus_examples:vue_object_lifecycle' %}" class="button is-primary is-outlined">
              <span>Vue Demo</span>
              <span class="icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="column">
      <div class="card h-100">
        <div class="card-image">
          <figure class="image is-3by2">
            <img src="{% static 'images/pegasus/celery-icon.png' %}" alt="Background Tasks">
          </figure>
        </div>
        <div class="card-content dashboard-card-content">
          <div class="content">
            <h3>Background Tasks</h3>
            <p>
              Support background, long-running, or scheduled tasks easily with a working Celery
              + front-end integration.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_examples:tasks' %}" class="button is-primary is-outlined">
              <span>View Tasks</span>
              <span class="icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="columns">
    <div class="column">
      <div class="card h-100">
        <div class="card-image">
          <figure class="image is-3by2">
            <img src="{% static 'images/undraw/undraw_analytics.svg' %}" alt="Charts">
          </figure>
        </div>
        <div class="card-content dashboard-card-content">
          <div class="content">
            <h3>Charts</h3>
            <p>
              Fully-integrated charts based on real data from your application.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_examples:charts' %}" class="button is-primary is-outlined">
              <span>View Charts</span>
              <span class="icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="column">
      <div class="card h-100">
        <div class="card-image">
          <figure class="image is-3by2">
            <img src="{% static 'images/pegasus/landing-page-screenshot-small.png' %}" alt="Landing Page">
          </figure>
        </div>
        <div class="card-content dashboard-card-content">
          <div class="content">
            <h3>Landing Page</h3>
            <p>
              A beautiful, responsive, and easy-to-customize landing page to help
              you tell your application's story.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_examples:landing_page' %}" class="button is-primary is-outlined">
              <span>View Landing Page</span>
              <span class="icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="column">
      <div class="card h-100">
        <div class="card-image">
          <figure class="image is-3by2">
            <img src="{% static 'images/pegasus/pricing-page-screenshot-small.png' %}" alt="Pricing Page">
          </figure>
        </div>
        <div class="card-content dashboard-card-content">
          <div class="content">
            <h3>Pricing Page</h3>
            <p>
              Communicate your application's value with a simple, flexible
              pricing page.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_examples:pricing_page' %}" class="button is-primary is-outlined">
              <span>View Pricing Page</span>
              <span class="icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="has-text-centered content">
    <p>
      ...more coming soon!
    </p>
  </div>
</section>
{% endblock %}

boilerplate/templates/pegasus/examples/tasks.html
{% extends "pegasus/examples/examples_base.html" %} {% load static %} {% block
app %}
<section class="section app-card">
  <h1 class="title">Tasks Example</h1>
  <h2 class="subtitle">
    Support background, long-running, or scheduled tasks easily with Celery
  </h2>
  <div class="content">
    <p>
      Most applications eventually need to perform tasks that take longer than a
      few seconds to complete, for example data imports/exports. If yours is one
      of these, you'll probably want to use
      <a href="http://www.celeryproject.org/">Celery</a> for the job to run in
      the background.
    </p>
    <p>
      This page is a complete example that creates tasks for a background Celery
      process and displays the progress below. It should provide a perfect
      example to build from.
    </p>
    <p>
      <strong>Kick off your first Celery task below!</strong>
    </p>
    <div class="buttons">
      <button class="button is-primary" id="task-starter">
        <span>Run Task</span>
        <span class="icon">
          <i class="fa fa-angle-double-right"></i>
        </span>
      </button>
    </div>
    <div class="progress-bar-demo">
      <div class="progress-wrapper">
        <div id="progress-bar" class="progress-bar">&nbsp;</div>
      </div>
      <div id="progress-bar-message">Waiting for progress to start...</div>
    </div>
    <p>
      For more information about how this works see:
      <a href="https://buildwithdjango.com/blog/post/celery-progress-bars/">
        Building Progress Bars for the Web with Django and Celery
      </a>
    </p>
  </div>
</section>
{% endblock %} {% block page_js %}
<script src="{% static 'celery_progress/celery_progress.js' %}"></script>
<script src="{% static 'js/app-bundle.js' %}"></script>
<script>
  const App = SiteJS.app;
  const apiUrl = "{% url 'pegasus_examples:tasks_api' %}";
  const progressUrl = "{% url 'celery_progress:task_status' 'task-id-stub' %}";
  document.addEventListener("DOMContentLoaded", function () {
    var trigger = document.getElementById("task-starter");
    trigger.addEventListener(
      "click",
      function (e) {
        e.preventDefault();
        var pb = document.getElementById("progress-bar");
        pb.style.display = "inherit";
        fetch(apiUrl, {
          method: "post",
          credentials: "same-origin",
          headers: {
            "X-CSRFToken": App.Cookies.get("csrftoken"),
          },
        })
          .then(function (response) {
            return response.text();
          })
          .then(function (text) {
            var taskUrl = progressUrl.replace("task-id-stub", text);
            CeleryProgressBar.initProgressBar(taskUrl, {
              onProgress: function (
                progressBarElement,
                progressBarMessageElement,
                progress
              ) {
                progressBarElement.style.width = progress.percent + "%";
                progressBarMessageElement.innerHTML =
                  progress.current + " of " + progress.total + " processed.";
              },
            });
          })
          .catch(function (error) {
            console.error("Request failed", error);
          });
        e.preventDefault();
      },
      false
    );
  });
</script>
{% endblock %}